package com.gdpu.myfriday2.model;

public class RoleUserKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_user.role_id
     *
     * @mbg.generated Fri Mar 27 16:45:25 CST 2020
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_user.user_id
     *
     * @mbg.generated Fri Mar 27 16:45:25 CST 2020
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_user.role_id
     *
     * @return the value of role_user.role_id
     *
     * @mbg.generated Fri Mar 27 16:45:25 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_user.role_id
     *
     * @param roleId the value for role_user.role_id
     *
     * @mbg.generated Fri Mar 27 16:45:25 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_user.user_id
     *
     * @return the value of role_user.user_id
     *
     * @mbg.generated Fri Mar 27 16:45:25 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_user.user_id
     *
     * @param userId the value for role_user.user_id
     *
     * @mbg.generated Fri Mar 27 16:45:25 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}