package com.gdpu.myfriday2.dao;

import com.gdpu.myfriday2.model.RoleUserExample;
import com.gdpu.myfriday2.model.RoleUserKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface RoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbg.generated Fri Mar 27 16:45:25 CST 2020
     */
    long countByExample(RoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbg.generated Fri Mar 27 16:45:25 CST 2020
     */
    int deleteByExample(RoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbg.generated Fri Mar 27 16:45:25 CST 2020
     */
    int deleteByPrimaryKey(RoleUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbg.generated Fri Mar 27 16:45:25 CST 2020
     */
    int insert(RoleUserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbg.generated Fri Mar 27 16:45:25 CST 2020
     */
    int insertSelective(RoleUserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbg.generated Fri Mar 27 16:45:25 CST 2020
     */
    List<RoleUserKey> selectByExample(RoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbg.generated Fri Mar 27 16:45:25 CST 2020
     */
    int updateByExampleSelective(@Param("record") RoleUserKey record, @Param("example") RoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbg.generated Fri Mar 27 16:45:25 CST 2020
     */
    int updateByExample(@Param("record") RoleUserKey record, @Param("example") RoleUserExample example);
}